### ISSUE TITLE
Cuda 10.1 compilation failed.

### ISSUE THREAD

**Issue by Dawlan** [GiuliaP/nsga2_cuda#2]
The version of CUDA I used was 10.1, but it doesn't seems to work.  
Could you tell me how to address the problem if you know the answer? thanks!

**Comment by GiuliaP** [comment]
@Dawlan Unfortunately, I am sorry but I cannot help. I fear that since this is a pretty old code, developed for CUDA 4 or 5, many things may need to be changed, in order to resume it and compile with more recent CUDA versions.
